name: Notify GitHub Contribution

on:
  schedule:
    - cron: '0 21 * * *'
    - cron: '0 23 * * *'
    - cron: '59 23 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Run notification script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
        LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      run: go run main.go
